# Generated by Django 3.2.8 on 2021-12-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Names')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('linkedin', models.URLField(max_length=100, verbose_name='Linkedin')),
                ('github', models.URLField(max_length=100, verbose_name='Github')),
                ('resume', models.FileField(upload_to='', verbose_name='Resume')),
            ],
        ),
    ]
